### ISSUE TITLE
Can not install pepper8 when Jinja2 is not installed in setup time

### ISSUE THREAD

**Issue by andras-tim** [myth/pepper8#2]
``` bash
$ pip install pepper8
```

```
Downloading/unpacking pepper8
  Downloading pepper8-1.0.4.tar.gz
  Running setup.py egg_info for package pepper8
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/build/pepper8/setup.py", line 6, in <module>
        from pepper8.main import VERSION
      File "pepper8/main.py", line 10, in <module>
        from pepper8.generator import HtmlGenerator
      File "pepper8/generator.py", line 8, in <module>
        from jinja2 import Template
    ImportError: No module named jinja2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>
  File "/build/pepper8/setup.py", line 6, in <module>
    from pepper8.main import VERSION
  File "pepper8/main.py", line 10, in <module>
    from pepper8.generator import HtmlGenerator
  File "pepper8/generator.py", line 8, in <module>
    from jinja2 import Template

ImportError: No module named jinja2

----------------------------------------
Command python setup.py egg_info failed with error code 1
```

_In other hand, the `jinja2` install in same time with `pepper8` isn't help._

**Comment by myth** [comment]
I can't seem to reproduce. What platform and Python/pip version are you using, so I can set up an identical environment?

**Comment by andras-tim** [comment]
Sorry for this issue. This caused by an old pip (1.0 installed by apt-get) on a Ubuntu Precise docker.

Thx!
